# DRAG
destination:
  server: https://kubernetes.default.svc
# The Git server to used by the application
source:
  # the source repository on git
  repoURL: http://gitea-127.0.0.1.sslip.io:30950/user-01/lingua-greeter-gitops
  # The branch/tag to use for the source repo
  targetRevision: main
# The Gitea Server configuration that will be used for GitOps
gitea:
  server:
    # the URL to reach git externally
    outClusterURL: http://gitea-127.0.0.1.sslip.io:30950
    # the URL to reach git internally
    inClusterURL: http://gitea-http.default.svc.cluster.local:30950
  # the gitea username
  username: user-01
  # the gitea password
  password: user-01@123

## Kafka
bitnami:
  kafka:
    version: 18.0.8
    namespace: kafka

 
## Lingua Greeter

replicaCount: 1

image:
  name: example/lingua-greeter
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets:
  - name: my-registry-creds
nameOverride: ""
fullnameOverride: ""

linguaGreeter:
  namespace: demo-apps
  kafka:
    bootstrap:
      servers: my-cluster-kafka.kafka:9092

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

imageCredentials:
  username:
  password:
  registry:
  email:

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    cpu: 200m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {}