# The Kubernetes Cluster where the resources wil be created
# Defaults to local cluster where ArgoCD is deployed
destination:
  server: https://kubernetes.default.svc
# The Git server to used by the application
source:
  # the source repository on git
  repoURL: http://gitea-127.0.0.1.sslip.io:30950/user-01/lingua-greeter-gitops
  # The branch/tag to use for the source repo
  targetRevision: main
# The Gitea Server configuration that will be used for GitOps
gitea:
  server:
    # the URL to reach git externally
    outClusterURL: http://gitea-127.0.0.1.sslip.io:30950
    # the URL to reach git internally
    inClusterURL: http://gitea-http.default.svc.cluster.local:30950
  # the gitea username
  username: user-01
  # the gitea password
  password: user-01@123
bitnami:
  kafka:
    version: 3.2.1
    namespace: kafka
linguaGreeter:
  namespace: demo-apps
