fullnameOverride: "lingua-greeter"
imageCredentials:
  registry: "${REGISTRY_NAME}"
  username: "${IMAGE_REGISTRY_USER}"
  password: "${IMAGE_REGISTRY_PASSWORD}"
image:
  # defaults to using local nexus registry deployed as part of DRAG stack
  name: "${REGISTRY_NAME}/example/lingua-greeter"
linguaGreeter:
  namespace: demo-apps
  kafka:
    bootstrap:
      servers: my-cluster-kafka.kafka:9092