fullnameOverride: "lingua-greeter"
imageCredentials:
  registry: "${REGISTRY_NAME}"
  username: "${IMAGE_REGISTRY_USER}"
  password: "${IMAGE_REGISTRY_PASSWORD}"
image:
  # defaults to using local nexus registry deployed as part of DRAG stack
  name: "${REGISTRY_NAME}/example/lingua-greeter"
google:
  application:
    credentials:
      file: "${GOOGLE_APPLICATION_CREDENTIALS}"
